# Generated by Django 2.0.4 on 2019-01-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='decription',
            new_name='description',
        ),
    ]
